name: Maven Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean test package

      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: target/my-app-1.0-SNAPSHOT-shaded.jar
